
spring.application.name=punto-de-venta-acc

server.port=8080
server.address=0.0.0.0

# Mongo para contenedores (usa el nombre del servicio 'mongo')
spring.data.mongodb.uri=mongodb://mongo:27017/posdb

# Cache
spring.cache.type=redis

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=5s

# TTL por defecto para las entradas en cache (5 minutos)
spring.cache.redis.time-to-live=300000


# Logs
logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.data.redis.connection=DEBUG
logging.level.org.s
pringframework.data.redis.core=DEBUG

# OpenTelemetry
# ---- MÉTRICAS (Micrometer -> OTLP/HTTP -> Mimir) ----
management.otlp.metrics.export.url=http://grafana-lgtm:4318/v1/metrics
management.metrics.export.otlp.step=10s   # opcional, para verlas más rápido en dev

# ---- TRAZAS (OTel -> OTLP/HTTP -> Tempo) ----
management.opentelemetry.tracing.export.otlp.endpoint=http://grafana-lgtm:4318/v1/traces

#===== Logs (si estás usando export OTLP de logs) =====
# Algunas guías lo exponen como logging.export..., otras como opentelemetry.logging...
# Con Spring Boot 4 + starter suele funcionar:
management.opentelemetry.logging.export.otlp.endpoint=http://grafana-lgtm:4318/v1/logs

# Muestreo (100% en dev; en prod bajarlo)
management.tracing.sampling.probability=1.0

# ---- LOG LEVELS ----
logging.level.org.springframework.boot.autoconfigure.opentelemetry=DEBUG





